# -*- coding: utf-8 -*-
"""Age.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16oc77QNbGukYt0j_3UDHzXBho3mbUaxT
"""

age=int(input("Enter your age: "))

years=100-age
months=years*12
days=years*365
weeks=years*52
hours=days*24
min=hours*60
sec=min*60

print(f"your Age: {age} years\nyou have {years} years,  {months} months,  {weeks} weeks,  {hours} hours, {min} min, and {sec} sec left to die sorry :(")