# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fzPPQ6yV8sFepHwKs7WpxHedEuw1LE3e
"""

import pandas
from pandas import DataFrame
import matplotlib.pyplot as plt

data = pandas.read_csv('Housing.csv')

data.describe()

x=DataFrame(data, columns=['area'])
y=DataFrame(data, columns=['bedrooms'])

plt.figure( figsize=(6,6) )
plt.scatter(x , y , alpha=0.3)
plt.title('Area size vs bedrooms size')
plt.xlabel('area size')
plt.ylabel('bedrooms size')
plt.show()
